### ISSUE TITLE
Exit code

### ISSUE THREAD

**Issue by vmeurisse** [Palisand/flow-error-suppressor#1]
Hi,

The command `flow-error-suppressor` always exit with a successful exit code.

Would it be possible to use exit code `2 ` like flow when their are some errors? This would simplify CI scripts a lot.

**Comment by Palisand** [comment]
It should definitely be possible and I'll get on it this week. I was ignoring stderr since I haven't set up any ci and since I get annoyed by npm's error messages (but that's easily solvable with `; exit 0` or `|| true`).

**Comment by Palisand** [comment]
@vmeurisse I would like to also include options for exiting with `2` for any errors or only for unsuppressed errors. In your opinion, is it better or worse to have non-zero exit codes by default?

Default: Exit with 0
`--error-on-any | -a` Exit with 2 for any flow errors.
`--error-on-shown | -s` Exit with 2 only for unsuppressed flow errors.

VS

Default: Exit with 2 for any flow errors
`--error-on-shown | -s` Exit with 2 only for unsuppressed flow errors.
`--exit-with-zero | -z` Always exit with 0 (so you don't have to resort to `; exit 0` in _`package.json`_`"scripts"`)

**Comment by Palisand** [comment]
@vmeurisse fixed and published
